//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClothesWashingData.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClothingArticle
    {
        public ClothingArticle()
        {
            this.Outfits = new HashSet<Outfit>();
            this.WashingSessions = new HashSet<WashingSession>();
        }
    
        public string Tag { get; set; }
        public ClothingArticleType Type { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> PurchaseDate { get; set; }
        public byte[] Picture { get; set; }
        public int IdState { get; set; }
    
        public virtual ClothingArticleState ClothingArticleState { get; set; }
        public virtual ICollection<Outfit> Outfits { get; set; }
        public virtual ICollection<WashingSession> WashingSessions { get; set; }
    }
}
