//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClothesWashingData.DataModel
{
    using System;
    
    public enum ClothingArticleType : byte
    {
        Blouse = 0,
        Shirt = 1,
        Trousers = 2,
        Shorts = 3,
        Tshirt = 4,
        Coat = 5,
        Underwear = 6,
        Undershirt = 7,
        Socks = 8,
        Cap = 9,
        Scarf = 10
    }
}
